# Generated by Django 3.2.6 on 2021-08-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='datefield',
            field=models.DateField(),
        ),
    ]
