# Generated by Django 3.2.6 on 2021-08-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_attendence_datefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='datefield',
            field=models.CharField(max_length=50),
        ),
    ]
